colorScheme = "cream"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableA11y = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
hotlinkFeatureImage = false
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"
favicon = false

[firebase]
apiKey = "AIzaSyC7c0UZ3xECttjMuZWh5AE41qOMLl5bAcg"
authDomain = "yiheng-blog-stats.firebaseapp.com"
projectId = "yiheng-blog-stats"
storageBucket = "yiheng-blog-stats.firebasestorage.app"
messagingSenderId = "674513555332"
appId = "1:674513555332:web:fcc2cd0ba68d0adc0017d1"
measurementId = "G-4X2W77Z3VD"
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
rssnext = { }
advertisement = { }

[header]
layout = "fixed-fill"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false
disableHeroImageFilter = false
orderByWeight = false

[article]
showDate = true
showViews = true
showLikes = true
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showAuthorBottom = true
showHero = false
showComments = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = true
showTaxonomies = true
showCategoryOnly = false
showAuthorsBadges = true
showWordCount = true
showZenMode = true
sharingLinks = [ "bluesky", "linkedin", "mastodon" ]

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
orderByWeight = false
cardView = false
cardViewScreenWidth = false
heroStyle = "basic"
