# netlify.toml
[build]
  command = "hugo mod get -u && hugo --gc --forceSyncStatic --theme blowfish -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.25.4"
  NODE_VERSION = "25.2.1"
  TZ = "UTC"  # Set to preferred timezone
  GIT_SUBMODULES = "true"

[context.production.environment]
  HUGO_VERSION = "0.153.3"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.153.3"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"

[functions]
  directory = "netlify/functions"