# netlify.toml
[build]
  command = "hugo mod get -u && hugo --gc --forceSyncStatic --theme blowfish -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "UTC"  # Set to preferred timezone
  GIT_SUBMODULES = "true"
  NETLIFY_ALLOWED_PUBLIC_KEYS = "AIza"
  SECRETS_SCAN_OMIT_PATHS = "config/_default/params/firebase"

[security]
  allowed_public_keys = [
    "AIza" # Firebase public API keys always start with this
  ]
  

[context.production.environment]
  HUGO_VERSION = "0.152.2"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.152.2"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
